Only generate boundaries for settlements.
PERF

build stats: Longman in LAD_Highland
                        time:   [615.10 µs 621.06 µs 627.18 µs]
                        change: [+0.1744% +0.9084% +1.6913%] (p = 0.02 < 0.05)
                        Change within noise threshold.
Found 15 outliers among 100 measurements (15.00%)
  6 (6.00%) high mild
  9 (9.00%) high severe

Benchmarking inverness/generate auto boundaries (and stats): Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 133.1s.
inverness/generate auto boundaries (and stats)
                        time:   [13.253 s 13.428 s 13.612 s]
                        change: [-40.584% -38.938% -37.165%] (p = 0.00 < 0.05)
                        Performance has improved.

build stats: Hilltown in LAD_Dundee City
                        time:   [845.68 µs 849.83 µs 854.32 µs]
                        change: [+2.2842% +2.7571% +3.2356%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 7 outliers among 100 measurements (7.00%)
  7 (7.00%) high mild

Benchmarking dundee/generate auto boundaries (and stats): Warming up for 3.0000 s
thread 'main' panicked at backend/benches/boundary_stats.rs:37:21:
assertion `left == right` failed
  left: 232
 right: 240
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace